FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-ui.txt .
RUN pip install -r requirements-ui.txt

COPY src src

EXPOSE 7860

CMD ["streamlit", "run", "src/ui.py", "--server.address", "0.0.0.0", "--server.port", "7860", "--server.headless", "true"]
